/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.meteo.ui.choosers;

import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import javafx.scene.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author SALIM
 */
public class LocationChooser extends javax.swing.JDialog {

    /**
     * Creates new form LocationChooser
     */
    String loc = "";

    public String getLoc() {
        return loc;
    }
    public LocationChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblmap.addMouseMotionListener(new MapListener());
        setLocationRelativeTo(null);
        setVisible(true);
        
    }
class MapListener implements MouseMotionListener{

        @Override
        public void mouseDragged(MouseEvent e) {
        }

        @Override
        public void mouseMoved(MouseEvent e) {
            getLocation(e.getX(),e.getY());
        }
        private void getLocation(int x, int y ){
if ((x>=120 && x<=160) && (y>=55 && y<=64)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
}
else if ((x>=181 && x<=236) && (y>=48 && y<=61)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=42 && x<=87) && (y>=89 && y<=97)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=108 && x<=161) && (y>=115 && y<=126)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=167 && x<=200) && (y>=98 && y<=113)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=24 && x<=60) && (y>=143 && y<=155)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=24 && x<=86) && (y>=162 && y<=172)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=122 && x<=154) && (y>=175 && y<=185)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=170 && x<=216) && (y>=179 && y<=192)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=11 && x<=59) && (y>=175 && y<=186)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=55 && x<=103) && (y>=186 && y<=197)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=108 && x<=143) && (y>=195 && y<=205)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=100 && x<=148) && (y>=213 && y<=224)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=109 && x<=164) && (y>=229 && y<=242)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=169 && x<=212) && (y>=233 && y<=245)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=123 && x<=143) && (y>=256 && y<=267)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=142 && x<=191) && (y>=263 && y<=276)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else if ((x>=149 && x<=178) && (y>=282 && y<=294)){
lblmap.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

}
else {
lblmap.setCursor(java.awt.Cursor.getDefaultCursor());

}
}

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmap = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtselection = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        lblmap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_1pn.png"))); // NOI18N
        lblmap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmapMouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im32/checkmark.png"))); // NOI18N
        jButton1.setText("Pick Selection");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("You Picked : ");

        txtselection.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtselection))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmap)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtselection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblmapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmapMouseClicked
        // TODO add your handling code here:
       txtselection.setText(getLocation(evt.getX(),evt.getY()));
       loc = getLocation(evt.getX(),evt.getY());
    }//GEN-LAST:event_lblmapMouseClicked
private String getLocation(int x, int y ){
if ((x>=120 && x<=160) && (y>=55 && y<=64)){
return "Moyale";
}
if ((x>=181 && x<=236) && (y>=48 && y<=61)){
return "Mandera";
}
if ((x>=42 && x<=87) && (y>=89 && y<=97)){
return "Lodwar";
}
if ((x>=108 && x<=161) && (y>=115 && y<=126)){
return "Marsabit";
}
if ((x>=167 && x<=200) && (y>=98 && y<=113)){
return "Wajir";
}
if ((x>=24 && x<=60) && (y>=143 && y<=155)){
return "Kitale";
}
if ((x>=24 && x<=86) && (y>=162 && y<=172)){
return "Kakamega";
}
if ((x>=122 && x<=154) && (y>=175 && y<=185)){
return "Meru";
}
if ((x>=170 && x<=216) && (y>=179 && y<=192)){
return "Garissa";
}
if ((x>=11 && x<=59) && (y>=175 && y<=186)){
return "Kisumu";
}
if ((x>=55 && x<=103) && (y>=186 && y<=197)){
return "Nakuru";
}
if ((x>=108 && x<=143) && (y>=195 && y<=205)){
return "Nyeri";
}
if ((x>=100 && x<=148) && (y>=213 && y<=224)){
return "Nairobi";
}
if ((x>=109 && x<=164) && (y>=229 && y<=242)){
return "Makindu";
}
if ((x>=169 && x<=212) && (y>=233 && y<=245)){
return "Lamu";
}
if ((x>=123 && x<=143) && (y>=256 && y<=267)){
return "Voi";
}
if ((x>=142 && x<=191) && (y>=263 && y<=276)){
return "Malindi";
}
if ((x>=149 && x<=178) && (y>=282 && y<=294)){
return "Mombasa";
}
return "";
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocationChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocationChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocationChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocationChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LocationChooser dialog = new LocationChooser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblmap;
    private javax.swing.JTextField txtselection;
    // End of variables declaration//GEN-END:variables
}
