/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.meteo.ui;

import com.meteo.controllers.UserController;
import com.meteo.models.User;
import com.meteo.utils.Mailer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SALIM
 */
public class frmmanageuser extends javax.swing.JDialog {

    /**
     * Creates new form frmmanageuser
     */
    DefaultTableModel model;
     Status status;
     Name name;
    public frmmanageuser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
     
        model = (DefaultTableModel)tblusers.getModel();
        status= (stat)->{
                    if (stat == 0){
                    return "Disabled";
                    }
                    else if (stat == 1) {
                    return "Enabled";
                    }
                    return "Disabled";
                    };
        name = (fname,lname)->{
        return fname + " " + lname;
        };
        tblusers.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseReleased(MouseEvent e){
         String type = "";
        int r = tblusers.rowAtPoint(e.getPoint());
        if (r>=0 && r<=tblusers.getRowCount()){
        tblusers.setRowSelectionInterval(r, r);
        }
        else {
        tblusers.clearSelection();
        }
        int index = tblusers.getSelectedRow();
        if (index < 0)
            return;
        if (e.isPopupTrigger() && e.getComponent() instanceof JTable){
         type = tblusers.getValueAt(tblusers.getSelectedRow(), 3).toString();
         String status = tblusers.getValueAt(tblusers.getSelectedRow(), 4).toString();
         JPopupMenu menu = adminpopup;
         if ("Administrator".equals(type)){
         mnudisable.setEnabled(false);
         mnuedit.setEnabled(false);
                  menu.show(e.getComponent(), e.getX(), e.getY());

         }
         else {
         mnudisable.setEnabled(true);
         mnuedit.setEnabled(true);
                  menu.show(e.getComponent(), e.getX(), e.getY());
         }
         if ("Enabled".equals(status)){
         mnudisable.setText("Disable User");
         for (ActionListener al : mnudisable.getActionListeners()){
         mnudisable.removeActionListener(al);
         }
         mnudisable.addActionListener(new ActionListener(){
             @Override
             public void actionPerformed(ActionEvent e) {
                 JOptionPane.showMessageDialog(null, "User Will be Disabled");
             }
         
         });
         }
         else {
         mnudisable.setText("Enable User");
          for (ActionListener al : mnudisable.getActionListeners()){
         mnudisable.removeActionListener(al);
         }
         mnudisable.addActionListener(new ActionListener(){
             @Override
             public void actionPerformed(ActionEvent e) {
                 JOptionPane.showMessageDialog(null, "User Will be Enabled");
             }
         
         });
         }
        }
        }
        });
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminpopup = new javax.swing.JPopupMenu();
        mnureset = new javax.swing.JMenuItem();
        mnudisable = new javax.swing.JMenuItem();
        mnuresend = new javax.swing.JMenuItem();
        mnuview = new javax.swing.JMenuItem();
        mnuedit = new javax.swing.JMenu();
        mnuname = new javax.swing.JMenuItem();
        mnuemail = new javax.swing.JMenuItem();
        mnuphone = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblusers = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSpinner4 = new javax.swing.JSpinner();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jSpinner5 = new javax.swing.JSpinner();

        mnureset.setText("Reset Password");
        adminpopup.add(mnureset);

        mnudisable.setText("Disable User");
        adminpopup.add(mnudisable);

        mnuresend.setText("Resend Password");
        adminpopup.add(mnuresend);

        mnuview.setText("View User Details");
        adminpopup.add(mnuview);

        mnuedit.setText("Edit User");

        mnuname.setText("Names");
        mnuedit.add(mnuname);

        mnuemail.setText("Email");
        mnuemail.setToolTipText("");
        mnuedit.add(mnuemail);

        mnuphone.setText("Phone");
        mnuedit.add(mnuphone);

        adminpopup.add(mnuedit);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tblusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Full Name", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblusers);

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel2.setText("Search :");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im32/plus.png"))); // NOI18N
        jButton1.setText("Add New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/im32/edit.png"))); // NOI18N
        jButton2.setText("Edit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsearch))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        jToolBar2.setRollover(true);

        jLabel3.setText("Filter Users  : ");
        jToolBar2.add(jLabel3);
        jToolBar2.add(filler1);

        jLabel4.setText("By Status");
        jToolBar2.add(jLabel4);
        jToolBar2.add(jSeparator2);

        jSpinner4.setModel(new javax.swing.SpinnerListModel(new String[] {"Enabled", "Disabled"}));
        jToolBar2.add(jSpinner4);
        jToolBar2.add(filler2);

        jLabel5.setText("By Type : ");
        jToolBar2.add(jLabel5);
        jToolBar2.add(jSeparator4);

        jSpinner5.setModel(new javax.swing.SpinnerListModel(new String[] {"Administrator", "Management", "Volunteer"}));
        jToolBar2.add(jSpinner5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmusers frm = new frmusers(null,true);
        List<User> usrs = frm.getUser();
        for (User user : usrs){
         String stat = status.getStatus(user.getStatus());
                Object[] userobj = {user.getId(),user.getUsername(),name.getName(user.getFname(), user.getLname()),user.getType(),stat};
                model.addRow(userobj);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_formWindowOpened

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        this.keyWordSearch(txtsearch.getText());
    }//GEN-LAST:event_txtsearchKeyReleased
    void refresh(){
    SwingWorker<List<User>,Void> refreshWorker = new SwingWorker<List<User>,Void>(){
        @Override
        protected List<User> doInBackground() throws Exception {
            UserController usc = new UserController();
            List<User> user = usc.getItems();
            return user;
            
        }
        @Override
        protected void done(){
            try {
                List<User> users = get();
                for (User user : users){
                    
                    String stat = status.getStatus(user.getStatus());
                Object[] userobj = {user.getId(),user.getUsername(),name.getName(user.getFname(), user.getLname()),user.getType(),stat};
                model.addRow(userobj);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(frmmanageuser.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                JOptionPane.showMessageDialog(frmmanageuser.this, ex.getMessage(), "Execution Exception", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    };
    refreshWorker.execute();
    }
    interface Status{
    public String getStatus(int stat);
    }
    interface Name{
    public String getName(String fname,String lname);
    }
    void edit(){
    
    }
    void changeState(String state, User user){
    
    }
    void resetPassword(User user){
    
    }
    void statusFilter(String Filter){}
    void typeFilter(String Filter){}
    void keyWordSearch(String keyword){
     List<User> users;
        SwingWorker<List<User>,Void> searchWorker = new SwingWorker<List<User>,Void>(){
        @Override
        protected List<User> doInBackground() throws Exception {
            UserController usc = new UserController();
            List<User> user = usc.keywordSearch(keyword);
            return user;
            
        }
        @Override
        protected void done(){
            try {
                List<User> users = get();
                model.setRowCount(0);
                for (User user : users){
                    
                String stat = status.getStatus(user.getStatus());
                Object[] userobj = {user.getId(),user.getUsername(),name.getName(user.getFname(), user.getLname()),user.getType(),stat};
                model.addRow(userobj);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(frmmanageuser.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                JOptionPane.showMessageDialog(frmmanageuser.this, ex.getMessage(), "Execution Exception", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    };
        searchWorker.execute();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmanageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmanageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmanageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmanageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmmanageuser dialog = new frmmanageuser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu adminpopup;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem mnudisable;
    private javax.swing.JMenu mnuedit;
    private javax.swing.JMenuItem mnuemail;
    private javax.swing.JMenuItem mnuname;
    private javax.swing.JMenuItem mnuphone;
    private javax.swing.JMenuItem mnuresend;
    private javax.swing.JMenuItem mnureset;
    private javax.swing.JMenuItem mnuview;
    private javax.swing.JTable tblusers;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
